[Main]
theme = cyborg
path = log.md
fontqryfam = Cascadia Code
fontqrysiz = 10
fontgptfam = Hack
fontgptsiz = 10
engine = groq/compound
btncolor = default
top_frame = 7
editor = mousepad
tempfile = temp.md
voice = nova
color = LightSkyBlue1
system = You are an expert coder and helpful technical assistant.
temper = 0.2
# Italics and Bold
md1 = green2
# Headings
md2 = green4
# `code`
md3 = gray
